[package]
name = "s12g-web"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
uuid = "0.7"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "uuid"]
